// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO5-TXofpXy4t5ZC1uuHY8118fZ9RKoJk',
    appId: '1:464469685896:web:3d8b5e2672eddd7cb4113d',
    messagingSenderId: '464469685896',
    projectId: 'appcutivo',
    authDomain: 'appcutivo.firebaseapp.com',
    storageBucket: 'appcutivo.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxBlEHo9x-xfsm8WyVxrKqtPJ-inS6HwA',
    appId: '1:464469685896:android:a15924453c38a4c1b4113d',
    messagingSenderId: '464469685896',
    projectId: 'appcutivo',
    storageBucket: 'appcutivo.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXHzhcmuAHJzw8KQ0UKQlqxMZKku2Uk0Y',
    appId: '1:464469685896:ios:51619d26f7e51c4fb4113d',
    messagingSenderId: '464469685896',
    projectId: 'appcutivo',
    storageBucket: 'appcutivo.firebasestorage.app',
    iosBundleId: 'com.example.appCultivo',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXHzhcmuAHJzw8KQ0UKQlqxMZKku2Uk0Y',
    appId: '1:464469685896:ios:51619d26f7e51c4fb4113d',
    messagingSenderId: '464469685896',
    projectId: 'appcutivo',
    storageBucket: 'appcutivo.firebasestorage.app',
    iosBundleId: 'com.example.appCultivo',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO5-TXofpXy4t5ZC1uuHY8118fZ9RKoJk',
    appId: '1:464469685896:web:3a1667ae06510d1db4113d',
    messagingSenderId: '464469685896',
    projectId: 'appcutivo',
    authDomain: 'appcutivo.firebaseapp.com',
    storageBucket: 'appcutivo.firebasestorage.app',
  );
}
